### ISSUE TITLE
Assets and localizations

### ISSUE THREAD

**Issue by akiarostami** [GraphCMS/gatsby-source-graphcms#195]
Hi,

We just moved our content from another CMS to GraphCMS, and we love it! But we just ran into a major issue that we can't figure out how to resolve.

We have many models and almost all of them have images (assets). We also have 2 locales. Our site is build with Gatsby and we use gatsby-source-graphcms.

All fields without "enabled localisation" return their default value, which is exactly what we expect. However, localisation is enabled for Assets by default and we can't turn it off, and they don't seem to have a fallback. How can we get the image (assets) value for non-default locales?

Your documentation [here](https://graphcms.com/blog/handling-localization-in-graphcms) specifically says:

`If localized assets are not added, then the fallback (default locale) asset will be served where applicable.
`

which is exactly what I need, but I can't get the fallback to default locale.

Thank you.

**Comment by notrab** [comment]
@akiarostami Perhaps @jpedroschmitz can help out on this one - if he's any experience.

It's been a while since I used this plugin but from what I recall some Gatsby limitations would require you to overwrite the Gatsby resolver for the plugin to fetch what you need.

Since Gatsby creates its own GraphQL layer, it doesn't work the same way as GraphCMS does.

**Comment by notrab** [comment]
Perhaps this issue will give you more context on this: https://github.com/GraphCMS/gatsby-source-graphcms/issues/164
