### ISSUE TITLE
on upgrading to Gatsby 4 return null on build

### ISSUE THREAD

**Issue by luciobenini** [GraphCMS/gatsby-source-graphcms#209]
After upgrading to Gatsby v4 and using the next repo, when build sites, markdownNode returns null.

`
"content": {
  "markdownNode": null
},
`

Tried in several projects, same results.

Thanks for any help.

**Comment by jpedroschmitz** [comment]
Hey @luciobenini, thanks for reporting it!

Do you have a GitHub repository? This way, it's easier to reproduce and find the bug.

**Comment by luciobenini** [comment]
Hi @jpedroschmitz the main repo is [pittica/site](https://github.com/pittica/site) but you need to upgrade gatsby to v4 and gatsby-source-graphcms to @next.
The issue is only on the mdx (RichText) types.

**Comment by jpedroschmitz** [comment]
Thanks a lot for the quick reply :D

I'll take a look into this issue and keep you posted here!

**Comment by notrab** [comment]
Hey @luciobenini have you enabled Embeds on your Rich Text field?

**Comment by luciobenini** [comment]
@notrab No. Embeds off.

**Comment by vinayakakv** [comment]
Facing the same issue on `gatsby build` with `downloadLocalImages: true`.

`gatsby develop` works fine, though.

**Comment by luciobenini** [comment]
Updated to 2.7.0-next.4 and still not working.
MDX and assets don't working when building.

**Comment by notrab** [comment]
Temp fix... Can you try this out to see if it helps with this issue? It might not, but it will resolve others. 🤞🏻 

If a Rich Text field has embeds enabled, this is going to be a bit weird to resolve, since the typename changes for that field that Gatsby was expecting.

When configuring the plugin, you must specify the ModelField for the embedded RichText.

For example, a Product model with the field Description would have configuration that looks like this:

```js
{
  resolve: 'gatsby-source-graphcms',
  options: {
    richTextEmbedTypeNames: ['ProductDescription'],
  }
}
```

If you have multiple Rich Text fields on multiple models, you'd add it to the array.

Users will also need to install `v2.7.0-next.6` too.

I'm aiming to get Gatsby to do this automatically by visiting the schema for those fields, but I've not used Gatsby in over a year, so I'll continue tomorrow.

**Comment by luciobenini** [comment]
#222 Please check on request
